### PR TITLE
Add vpn config to security group component of the template

### PR DESCRIPTION
**Pull request by AwkwardBen**
This will allow us to create template which can connect to rds instance from host device via the vpn.

### CODE REVIEW

**Comment by jon-shanks** [comment]
Hi, this looks like it is just postgresql RDS as oppose RDS, but just wondering why we would need to connect to a DB on the VPN. We probably shouldn't do this generally as it means someone could bypass an application and dump loads of data out without any visibility or audit, so long as they were on the vpn subnet. Seems like a security risk really.

**Comment by Joseph-Irving** [comment]
@jon-shanks I believe this PR relates to https://github.com/UKHomeOffice/hosting-platform-bau/issues/1060

**Comment by jon-shanks** [comment]
Ah right, quite a lot of info. I guess as it's tied to a specific RDS the risk is mitigated. Can we make this more boolean for someone to set at the top i.e. vpn_access and then make it conditional as oppose making this generic, we don't want really people making all RDS instance VPN accessible, it should be off by default and someone can turn it on if they really want it. I will add to the discussion though as there are other considerations in that thread

**Comment by jon-shanks** [comment]
Also can we rename the file in the process to be postgresql-rds-temp as RDS can be many DB types

**Comment by daniel-ac-martin** [comment]
@jon-shanks: With regards to dumping data, they would still need DB creds. And even with the status quo, if they have access to k8s they can still dump out all the data.

**Pull request merged**
